#' Find local maximum peaks
#' 
#' Find local maximum peaks in EEM data
#' 
#' @param x EEM data generated by \code{\link{readEEM}} function.
#' @param n sample number. The number should not exceed \code{length(EEM)}.
#' @param threshold threshold value. Lower the value to cover low peaks.
#' 
#' @return A dataframe of local maximum peaks
#' 
#' @examples
#' data(applejuice)
#' findLocalMax(applejuice, 1) 
#' 
#' @export
#' 
#' @importFrom reshape2 melt
#' @importFrom sp point.in.polygon
findLocalMax <- function(EEM, n, threshold = 0.7){
        # stop if EEM is not of class 'EEM'
        if (!(class(EEM) %in% "EEM")) stop("EEM must of class 'EEM")
    
        # get information from EEM
        data <- EEM[[n]]
        
        # get contourLines
        x <- as.numeric(colnames(data)) # EX
        y <- as.numeric(rownames(data)) # EM
        z <- t(as.matrix(data))
        cLine <- contourLines(x, y, z, nlevels = 100) 
        
        # melt z
        z_melted <- melt(z)
        names(z_melted)[1:2] <- c("EX", "EM")
        
        # retrieve high contours
        level <- sapply(cLine, function(x) x$level)
        dif <- diff(range(level))
        cutoff <- dif * threshold
        value <- min(level[level > cutoff])
        cLine_selected <- cLine[level == value]
        
        # find max value for each contour
        local_max <- data.frame(EX = numeric(), EM = numeric(), value = numeric(), 
                                stringsAsFactors = FALSE)
        I <- length(cLine_selected)
        for (i in 1:I) {
            pol <- cLine_selected[i]
            pol.x <- as.numeric(sapply(pol, function(x) x$x))
            pol.y <- as.numeric(sapply(pol, function(x) x$y))
            index <- point.in.polygon(z_melted$EX, z_melted$EM, pol.x, pol.y) > 0
            if (sum(index) == 0){ 
                # when there is no real point within polygon, give NA value
                local_max[i,] <- NA
            } else {
                MAX <- max(z_melted$value[index])
                MAX.index <- which(z_melted$value == MAX)
                local_max[i,] <- z_melted[MAX.index,]
            }
        }
        row.names(local_max) <- NULL
        return(local_max)
    }